driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.12.15 # a chef release without yum built in

verifier:
  name: inspec

platforms:
- name: centos-5.11
- name: centos-6.8
- name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[yum-epel::default]
