sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

services: docker

branches:
  only:
  - master

env:
  matrix:
  - INSTANCE=default-centos-5
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script: KITCHEN_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - before_script:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      - /opt/chefdk/embedded/bin/chef --version
      - /opt/chefdk/embedded/bin/cookstyle --version
      - /opt/chefdk/embedded/bin/foodcritic --version
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
